### ISSUE TITLE
Error in cran.toc.rds

### ISSUE THREAD

**Issue by JamesLMacAulay** [CredibilityLab/groundhog#100]
I just started using groundhog to help get an environment where I can update and build a package for a 3.5 shiny server application.

The groundhog package installs fine for R 3.5, and I was able to point to a custom groundhog directory, however, when I try to use the groundhog.library() function, I get the following error:

```
> groundhog.library(pkgs, groundhog.day)
Error in readRDS(cran.toc.path) : embedded nul in string: 'multitap\0\t'
>
```

When I try to access the 3 rds files that groundhog has downloaded to my groundhog directory directly, I see the following:

```
> cran.times <- readRDS("c:/_dev/R/groundhog/cran.times.rds")
Error in readRDS("c:/_dev/R/groundhog/cran.times.rds") : 
  error reading from connection
In addition: Warning message:
In readRDS("c:/_dev/R/groundhog/cran.times.rds") :
  lzma decoder corrupt data
> cran.toc <- readRDS("c:/_dev/R/groundhog/cran.toc.rds")
Error in readRDS("c:/_dev/R/groundhog/cran.toc.rds") : 
  embedded nul in string: 'multitap\0\t'
> windows35 <- readRDS("c:/_dev/R/groundhog/windows35.rds")
Error in readRDS("c:/_dev/R/groundhog/windows35.rds") : 
  error reading from connection
In addition: Warning message:
In readRDS("c:/_dev/R/groundhog/windows35.rds") :
  invalid or incomplete compressed data
>
```

**Comment by urisohn** [comment]
Hi. One possibility is that there was a short term issue with the server delivering the .rds files.
Could you try again? I was able to reproduce the error, but then shortly after it was working fine again.  So that's a possible explanation.

I just installed v3.1.0 in R-3.5 no problem

**Comment by JamesLMacAulay** [comment]
I removed the groundhog package, and deleted all associated files (i.e. the groundhog folder).
I was able to reinstall, but I still get the exact same error messages.

```
Restarting R session...

> install.packages("groundhog")
Installing package into ‘C:/_dev/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/bin/windows/contrib/3.5:
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/PACKAGES'
installing the source package ‘groundhog’

trying URL 'https://cran.rstudio.com/src/contrib/groundhog_3.1.0.tar.gz'
Content type 'application/x-gzip' length 79083 bytes (77 KB)
downloaded 77 KB

* installing *source* package 'groundhog' ...
** package 'groundhog' successfully unpacked and MD5 sums checked
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'groundhog'
    finding HTML links ... done
    cross.toc                               html  
    get.groundhog.folder                    html  
    get.snowball                            html  
    groundhog.library                       html  
    meta.groundhog                          html  
    restore.library                         html  
    set.groundhog.folder                    html  
    toc                                     html  
    try.renaming.method.again               html  
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (groundhog)
In R CMD INSTALL

The downloaded source packages are in
	‘C:\Users\jmacaulay\AppData\Local\Temp\RtmpqMmZUm\downloaded_packages’
> library(groundhog)
Attached: 'Groundhog' (Version: 3.1.0)
Tips and troubleshooting: https://groundhogR.com
> groundhog.day <- "2018-08-01"
> groundhog.path <- "c:/_dev/R/groundhog/"
> set.groundhog.folder(groundhog.path)

Groundhog folder set to: 'c:/_dev/R/groundhog/

Downloading database with information for all CRAN packages ever published
trying URL 'http://s3.wasabisys.com/groundhog/cran.toc.rds'
Content type 'application/octet-stream' length 2028296 bytes (1.9 MB)
downloaded 1.9 MB

Downloading database with installation times for all source packages on CRAN
trying URL 'http://s3.wasabisys.com/groundhog/cran.times.rds'
Content type 'application/octet-stream' length 810716 bytes (791 KB)
downloaded 791 KB

Downloading database will URLs for relevant binaries on GRAN
trying URL 'http://gran.groundhogr.com/toc/windows35.rds'
Content type 'application/octet-stream' length 258925 bytes (252 KB)
downloaded 252 KB

Error in readRDS(cran.toc.path) : embedded nul in string: 'multitap\0\t'
> 
```

I can continue to try throughout the day to see if there is any change.  Is there a different place that I could grab the corrupted files to perhaps get a working set?

**Comment by urisohn** [comment]
Ok, can reproduce again. I think the issue went away coincidentally before.
I have a hunch that the daily updated .rds file, which is a database of all packages on CRAN, gets corrupted when it attempts  to update and CRAN is not adding packages (CRAN is on vacation right now). I will look into this ASAP, hopefully by tomorrow.

**Comment by urisohn** [comment]
OK. That hypothesis was wrong, the files on the server are fine and CRAN's vacation period has nothing to do with this.

It has to do with how R versions before 3.6 download files. 

When the necessary .rds files are downloaded in R-3.5 they get corrupted.  

The fix is simple, currently testing  but CRAN is on vacation.

In the interim you can fix the problem by hand, by replacing the .rds file with files you download by hand.

You can use a browser, and download these 3 files, saving them into the location groundhog put them:
https://groundhogr.com/cran.toc.rds
https://groundhogr.com/cran.times.rds
https://groundhogr.com/gran.toc/windows35.rds

I think you can also do it within R:

```
 download.file("https://groundhogr.com/cran.toc.rds",      'c:/_dev/R/groundhog/cran.toc.rds',mode='wb')
 download.file("https://groundhogr.com/cran.times.rds",   'c:/_dev/R/groundhog/cran.times.rds',mode='wb')
 download.file("https://groundhogr.com/gran.toc/windows35.rds", 'c:/_dev/R/groundhog/windows35.rds', mode='wb')

```

**Comment by JamesLMacAulay** [comment]
Thank you!  The R code you provided to get the uncorrupted rds files worked, thank you very much!  I'm excited to have GRAN+groundhog available.
