### ISSUE TITLE
Clear the preset options?

### ISSUE THREAD

**Issue by skolenik** [CredibilityLab/groundhog#108]
Thank you for your work on putting this package together and maintaining GRAN!

Apparently, `.onLoad` a lot of stuff happening with the settings stored in the previous sessions. In this particular case, I had to log on as another user (who does not have the write access to the `groundhog` directories used earlier), and the library load fails:

```
> library(groundhog)
Error: package or namespace load failed for ‘groundhog’:
 .onLoad failed in loadNamespace() for 'groundhog', details:
  call: file(file, ifelse(append, "a", "w"))
  error: cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file 'D:/groundhog/cookies/check_groundhog_version.csv': Permission denied
```

I could not find the documentation of what the options are that need to be cleared so that I could load the package and start with a different set of intermediate folders (which is what I need to do at the moment).

**Comment by urisohn** [comment]
Ok, happy to try to help.
What exactly are you changing between sessions?
Everything groundhog saves goes to the folder set as groundhog's folder `get.groundhog.folder()` will reveal that.
A file outside of it stores where that folder is. If you were to delete that file you would get a fresh restart.
That file is called `current_groundhog_folder.txt`

Let me know if this addresses the issue you are having.
