### ISSUE TITLE
dplyr description file missing... but how?

### ISSUE THREAD

**Issue by HedvigS** [CredibilityLab/groundhog#109]
I've gotten:

```
> groundhog_date = "2023-07-17"
> 
> groundhog.library(pkg = "dplyr", groundhog_date)
Error in x$Version : $ operator is invalid for atomic vectors
In addition: Warning messages:
1: In FUN(X[[i]], ...) :
  DESCRIPTION file of package 'dplyr' is missing or broken
2: In FUN(X[[i]], ...) :
  DESCRIPTION file of package 'dplyr' is missing or broken

```

I guess the problem is somehow with dplyr at that date, but I'd be grateful for any advice here since I've never encountered this before.

**Comment by HedvigS** [comment]
Problem persist with other random dates I tried that are more recent. groundhog problem?

**Comment by urisohn** [comment]
I cannot reproduce the problem, tried both Windows and Mac
1) Is this the very first thing you run after starting a new R session?
2) Do you want to try setting temporarily a new groundhog folder
```
gf=get.groundhog.folder()                                  #save current location of groundhog folder
set.groundhog.folder(paste0(gf,"_TEMP"))         #change it 
groundhog.library('dplyr','2023-07-17')
set.groundhog.folder(gf)                                   #change it back
```

**Comment by HedvigS** [comment]
I only get this error on one of my two machines, not really sure why. Will be returning to it in a few days, I'll try your suggestions then!
