### ISSUE TITLE
How to install data.table from source and have multi-threading enabled

### ISSUE THREAD

**Issue by vronizor** [CredibilityLab/groundhog#111]
Hi, Thanks for the great package! Currently integrating it to my projects and very happy to be able to ground my libraries' versions.

I am having an issue with `data.table`, however. When I usually install it on my machine (Mac, Apple Silicon), I have to install from source in order to enable multi-threading (I follow the [official `data.table` guide](https://github.com/Rdatatable/data.table/wiki/Installation#openmp-enabled-compiler-for-mac)). However, when I install `data.table` using `groundhog` (`groundhog.library("data.table", groundhog.day, force.source.main = T)`), I am unable to get a multi-threaded version installed and loaded. The installation from source seems to work fine, tho. I tried `setDTthreads(threads = 5)` after installation but to no avail. 

Any idea how this could be solved? Let me know if I should provide more details on my machine and/or the installation output.

**Comment by urisohn** [comment]
I am not a user of data.table so will indeed need more details.
Could you send me the code you execute?
So the groundhog command, including the set of pkgs being installed/loaded and date, and then the line of code that produces the error with data.table? 
Also if you could confirm that the version of data.table you install from source without groundhog, which presumably works with multithreading, and the one you install with groundhog, which does not, is the same version?
