### ISSUE TITLE
Using https instead of http

### ISSUE THREAD

**Issue by uzpaka** [CredibilityLab/groundhog#113]
Hi,

First of all, thanks for this initiative, it looks really promising!

I have the following issue: Due to security measures, my company laptop does not allow downloads from http links such as:
http://gran.groundhogr.com/windows/4.1/2021-06-02/rio_0.5.26.zip

Using https does not work due to a certificate problem on your side.

Could you therefore provide https links?

**Comment by urisohn** [comment]
This is usefu, i think it may related to another open issue of inability to download files.
I am contacting support to try to enable https on the S3 bucket that has all the GRAN files. I can imagine this taking a few days to get resolved.

**Comment by urisohn** [comment]
Update: i setup cloudfare to provide https to GRAN. So you should be able to access files now
https://gran.groundhogr.com/windows/4.1/2021-06-02/rio_0.5.26.zip

But for not groundhog the package still has hardcoded the http

The development version on github does already rely on https but the one on CRAN won't be updated till later this week or next (I need to finalize testing other changes that were in the works)

**Comment by urisohn** [comment]
Groundhog 3.2.0 now on CRAN,addressed this.
