### ISSUE TITLE
Github Package cloning doesnt work

### ISSUE THREAD

**Issue by maxpi99** [CredibilityLab/groundhog#118]
I tried to load a github package with groundhog and i get the following error. When I use the git2r::clone directly to a certain path it works however.
![grafik](https://github.com/CredibilityLab/groundhog/assets/98280131/647e32e4-259f-4f22-af1a-073e677ad0e2)

**Comment by urisohn** [comment]
just to confirm, you use the same clone_path in both cases? it sounds like a folder permission issue, maybe try setting set.groundhog.folder() to one you are sure you have access to to rule that possibility out?

**Comment by maxpi99** [comment]
Sorry i forgot that, no its not the same folder. But it should be a folder permission problem, since all cran packages were installed and load into the same folder
![grafik](https://github.com/CredibilityLab/groundhog/assets/98280131/8aaca180-5569-451b-9dc4-0ebaae20d578)
![grafik](https://github.com/CredibilityLab/groundhog/assets/98280131/1c7236f8-aeb1-4e1a-af7b-85c807999a93)

**Comment by urisohn** [comment]
I think you have a space after the period in the name of the package, could that be the problem?
quanteda._sentiment vs.
quanteda.sentiment

**Comment by maxpi99** [comment]
i checked and it looks like it but there is no space between the period and the name.
here it the copied code
groundhog.library("github::quanteda/quanteda.sentiment", '2024-05-01',force.install = T)

**Comment by urisohn** [comment]
ok, thanks for checking.
I think it has to do with configuration of git
I looked this up and chatGPT had some useful tips, the first time it answers for Unix, i then tell it to swith to windows advice, I think this should take care of it

https://chatgpt.com/share/4ab3891a-0237-4677-9613-00f7e8961804
