### ISSUE TITLE
loading fails under R_REPOSITORIES=NULL

### ISSUE THREAD

**Issue by bastistician** [CredibilityLab/groundhog#122]
groundhog's `.onLoad()` is not robust against a possible empty "repos" setting, i.e. `options(repos=character())`, for instance if running R under `R_REPOSITORIES=NULL`.
I see:
```
** testing if installed package can be loaded
Error: package or namespace load failed for 'groundhog':
 .onLoad failed in loadNamespace() for 'groundhog', details:
  call: regexpr("http", r)[[1]]
  error: subscript out of bounds
```
which seems to come from `set.default.mirror()` here:
https://github.com/CredibilityLab/groundhog/blob/5667de665d9a0a30ff45feeafcd70bafcb8b6cea/R/utils.R#L622

**Comment by urisohn** [comment]
Thanks
Fixed: https://github.com/CredibilityLab/groundhog/commit/45f89ba5fbd8a232c8f06566bb105d25d48c80f1

**Comment by bastistician** [comment]
Confirmed:
```
** testing if installed package can be loaded from final location
groundhog says: No default repository found, setting to 'http://cran.r-project.org/'
* DONE (groundhog)
```
Any plans to release the fixed version? Thanks!

**Comment by urisohn** [comment]
probably later this month, one more edit i want to do involving github pkgs

**Comment by urisohn** [comment]
v3.2.2 on cran
