### ISSUE TITLE
Possible other package sources in the future

### ISSUE THREAD

**Issue by Bisaloo** [CredibilityLab/groundhog#34]
Packages are permanently archived in other places, which might be alternatives to MRAN in the future:

- https://packagemanager.rstudio.com/ 
    * pros: provide binaries for most linux distributions
    * cons: doesn't archive every day
- https://github.com/cran
    * only archive new versions
    * may take some time to update

**Comment by jl5000** [comment]
Some of us don't have RTools on our work environments, so we are very reliant on binaries. If these could come from other sources it would be useful.

**Comment by urisohn** [comment]
You may be thinking of a different issue than we had here in mind. This was about growing beyond CRAN which for a while it is not going to be considered.  For CRAN we try to maximize odds of calling on binaries by using MRAN. Binaries for source pacakges on CRAN are not available beyond MRAN i don't think 

> Some of us don't have RTools on our work environments, so we are very reliant on binaries. If these could come from other sources it would be useful.

**Comment by urisohn** [comment]
i think for now, if a binary of a CRAN package exists, it is guaranteed to be on MRAN. These are backup venues in case that were to change I think.
