### ISSUE TITLE
Dependency version locking for packages

### ISSUE THREAD

**Issue by shearerp** [CredibilityLab/groundhog#60]
A major reproducibility headache for R package developers is, they cannot rely on older versions of a dependency (R package) being installed on a system, since R has historically not made it easy for different versions of a package to be installed and used side-by-side. Groundhog appears to have solved that, but it isn't clear if that in itself is enough to resolve the package dependency issue. Is addressing that within groundhog's scope?

(Note: it's possible this issue is impossible to fully resolve, if R simply doesn't have the capability to run different versions of the same package in the same session. For example, if package A requires version 1 of Package C, and package B requires version 2, you can't use both package A and package B in the same session. I think R does in fact have this limitation but not 100% sure.)

**Comment by urisohn** [comment]
I am not sure I know what you have in mind with 'package dependency issue'. 

With groundhog you can have two (or more) versions of the same package installed, and when you load a version, all dependencies are loaded as current when that version was current (per the date in the groundhog.library() command). 

But, it is not possible in R to simultaneously load two versions of the same package within a session (how would R know which version of the package function you are referring to?). 

One could within the code itself load and then unload a version, then load another version. But this can be impractical if the version one wishes to unload is a dependency of another loaded package, or has .dlls associated with it, for the unloading will fail if done directly. INstead, one will need to unload those reverse dependencies first, then unload the package version of interest, then unload the .dlls.
