### ISSUE TITLE
`groundhog.library()` intermittent failure when loading `Matrix`

### ISSUE THREAD

**Issue by jimvine** [CredibilityLab/groundhog#64]
I was going to title this indicating that the failure occurred when `pkg` or `date` area specified with double quotes but succeeds with single quotes. However, having restarted my R session and re-run the command a bunch more times, I'm now not sure whether that is a reliable pattern: I have seen the command working with the package name specified in double quotes, and I have seen it fail with the package name in single quotes. So this may be a red herring.

---
System info:

`Loaded 'groundhog' (version:1.2.0) using R-4.0.3`
Windows 10.
R Studio 1.4.1103.

---

I have this code at the head of my file:

```
library(groundhog)
groundhog.day <- "2021-02-02"
groundhog.library("Matrix", groundhog.day)
```

This (mostly) fails with an error:

```
groundhog says:
1 of the 2 packages needed by 'Matrix_1.3-2' are currently loaded, but not with the version that is needed.
Loaded: Matrix_1.2-18
Needed: Matrix_1.3-2

To solve this: restart the R session. Note: you will need to do 'library(groundhog)' again.

In R Studio press: CTRL/CMD-SHIFT-F10
The package 'Matrix_1.3-2' was *NOT* loaded


       IMPORTANT: if you see this message after having restarted your R session,
       it means one of the packages you are loading does not properly reference
       a package it needs (in its 'DESCRIPTION' file).
       To solve this, you need to restart the session again, CTRL-SHIFT-F10,
       then run the code below **BEFORE** loading the packages you want to load:

       groundhog.library('Matrix','2021-02-02')
```

I looked at the command suggested in the last line of the error message and thought that it seemed unlikely to help since it looked equivalent to what my code said. But still, I tried it and was pretty surprised to find it worked.

Over a few more restarts of the R session, I narrowed down the differences (trying both the date field and the pkg field). In my experiments, it seemed like I found that if either the pkg or date value were specified with double quotes, the command failed with the same error. If the date was specified as a named variable it succeeds (even if that was defined with double quotes).

```
groundhog.day <- "2021-02-02"

# MOSTLY FAILS:
groundhog.library('Matrix', "2021-02-02")
groundhog.library("Matrix", "2021-02-02")
groundhog.library("Matrix", '2021-02-02')
groundhog.library("Matrix", groundhog.day)

# MOSTLY SUCCEEDS:
groundhog.library('Matrix', '2021-02-02')
groundhog.library('Matrix', groundhog.day)
```

As I say, this association may be spurious. I am certain that the package loading sometimes works and sometimes does not work using variants of the command that I would normally expect to be equivalent. I know that I have seen a tendency (but not, now, a hard-and-fast rule) that it seems to fail more often with double quotes than single. But I have weak confidence in whether that's actually the material factor in why this sometimes succeeds and sometimes fails.

I should also note that I am loading about 10 packages using groundhog. It is only Matrix that is throwing this error. The others are all loading fine. (For the rest I use the names in double quotes and the date as the `groundhog.day` variable I've specified.)

**Comment by urisohn** [comment]
I think the quotes is almost surely a red herring. Something is leading the 'Matrix' in your local library to be loaded before you run the groundhog command, and sometimes you execute groundhog.libary() before vs after that has been succesfully loaded in your environment
1) Is this an .r or .rmd script? (R Studio loads some things automatically in .rmd)
2) Do you run any code before that call? Load any package in any way?

**Comment by jimvine** [comment]
It's an Rmd script.

In my tests I have been running the code immediately after restarting the R session (Ctrl+Shift+F10). I.e., just `library(groundhog)`, setting `groundhog.day` and then the call to `groundhog.library()` to load `Matrix` in whatever form.

After each restart, I was running the test by selecting those 3 lines of code in the Rmd pane and pressing Ctrl+Enter. So I'm now (knowingly) running any code or loading any packages beforehand.

(In my production code, I was loading Matrix further down the pecking order, but moved it to the top for the purposes of testing.)

**Comment by jimvine** [comment]
PS: The only things above the code for loading groundhog in the file are a YAML header and a chunk (that I'm not knowingly running) that says `knitr::opts_chunk$set(echo = TRUE)`.

The contents of the YAML header are very bland. No complex code-like values, not even dynamically setting the date:

```
title: "Data import etc"
author: "Jim Vine"
date: "07/12/2020"
output: html_document
```

**Comment by urisohn** [comment]
Ok, so R Studio is loading some packages without your awareness, I am working right now on making groundhog be robust to this so perfect timing. Could you 
library(groundhog)
#wait 5 seconds
sessionInfo()

And see all packages that automatically loaded at that point?
Thanks if you can

**Comment by jimvine** [comment]
Sorry, I couldn't get back to this last week.

I have tried restarting R about 10 times and running this code today, and each time it has succeeded. I don't know whether the information you asked for is still useful, given that the error isn't currently being triggered on my system. But in case it is:

```
> library(groundhog)
Loaded 'groundhog' (version:1.2.0) using R-4.0.3
Path to folder where downloaded packages are saved: 'C:/Users/[USERNAME]/Documents/R_groundhog/groundhog_library/'.
To change its location: 'set.groundhog.folder(<path>)'
     >>> If you encounter errors using groundhog: http://groundhogR.com/troubleshooting
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] groundhog_1.2.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6      crayon_1.4.0    lifecycle_0.2.0 magrittr_2.0.1  pillar_1.4.7   
 [6] rlang_0.4.10    vctrs_0.3.6     ellipsis_0.3.1  forcats_0.5.1   tools_4.0.3    
[11] hms_1.0.0       xfun_0.20       compiler_4.0.3  pkgconfig_2.0.3 knitr_1.31     
[16] haven_2.3.1     tibble_3.0.6   
```

**Comment by urisohn** [comment]
Thanks. This is  a surprising behavior by R Studio that I am trying to understand. Even after a CTRl-SHIFT-F10 it reloads a series of packages automatically, getting in the way of version control. I cannot reproduce that so hard to debug. Do you have your environment empty? So if you were to clear everything, i wonder if those packages (haven, tibble, etc) would still get loaded for some reason.

So something like
` rm(list = ls())`
CTRL-SHIFT-F10
`sessionInfo()`

If you can try that, it would be great

**Comment by urisohn** [comment]
(btw, while your code is running succesfully, there is still an issue that you have several packages loaded without you requesting them, so if you wanted to do version control on haven or tibble or hms, you couldn't)

**Comment by jimvine** [comment]
I think you are right that this is something R Studio is doing. Or that I am inadvertently causing R Studio to do.

Below, I'm pasting the whole of the contents of my Console on a fresh open of R Studio. Here's what I did:

1. Emptied the environment (`rm(list = ls())`)
2. Restarted R (Ctrl Shift F10)
3. Check there's nothing unexpected loaded already `sessionInfo()`
4. Entered `library(groundhog)` **directly into the console**.
5. See what's loaded (nothing unexpected) using `sessionInfo()` again.
6. Load `Matrix` with `groundhog.library()`
7. `sessionInfo()` again (none of the R Studio loaded things are there)
8. Empty the Environment again
9. New R session again
10. Run the three lines of code **by highlighting them in the Rmd and hitting Ctrl+Enter**. I notice in the Console that R Studio is also running the code from the only previous chunk (`knitr::opts_chunk$set(echo = TRUE)`) that I definitely didn't have selected.
11. `sessionInfo()` again, showing all the extra packages.

I have, however, subsequently tried commenting out the `knitr` command so that the first chunk has no run code, and using the Ctrl+Enter method I still ended up with the bunch of packages showing in `sessionInfo()`.

And then, I tried deleting the whole of that first chunk, and I think that makes the problem go away. (I tried about 6 times, restarting R session and running the chunk or Ctrl+Enter on the 3 lines of code, and never got the packages showing up in `sessionInfo()`.)

And adding a new, completely empty, chunk above the chunk where I'm doing my groundhog commands makes it come back, but intermittently. For each test I: 

a. restart R; 
b. run `sessionInfo()` to check that the packages aren't loaded (they aren't);
c. run the chunk that contains 3 lines to load groundhog, set groundhog.day and the load Matrix using grounhog;
d. run `sessionInfo()` again.

About half the time it just shows the expected packages and half the time it shows the long unexpected list.

The new chunk I added is purely three backticks, `{r}`, a couple of carriage returns, and then three more backticks. 

```
R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.


R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> rm(list = ls())

Restarting R session...

> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.3 tools_4.0.3   
> library(groundhog)
Loaded 'groundhog' (version:1.2.0) using R-4.0.3
Path to folder where downloaded packages are saved: 'C:/Users/[USERNAME]/Documents/R_groundhog/groundhog_library/'.
To change its location: 'set.groundhog.folder(<path>)'
     >>> If you encounter errors using groundhog: http://groundhogR.com/troubleshooting
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] groundhog_1.2.0

loaded via a namespace (and not attached):
[1] compiler_4.0.3 tools_4.0.3   
> groundhog.day <- "2021-02-02"
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] groundhog_1.2.0

loaded via a namespace (and not attached):
[1] compiler_4.0.3 tools_4.0.3   
> groundhog.library('Matrix', groundhog.day)
groundhog says: successfully loaded 'Matrix_1.3-2'.
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Matrix_1.3-2    groundhog_1.2.0

loaded via a namespace (and not attached):
[1] compiler_4.0.3  tools_4.0.3     grid_4.0.3      lattice_0.20-41
> rm(list = ls())

Restarting R session...

> knitr::opts_chunk$set(echo = TRUE)
> 
> 
> 
> library(groundhog)
Loaded 'groundhog' (version:1.2.0) using R-4.0.3
Path to folder where downloaded packages are saved: 'C:/Users/[USERNAME]/Documents/R_groundhog/groundhog_library/'.
To change its location: 'set.groundhog.folder(<path>)'
     >>> If you encounter errors using groundhog: http://groundhogR.com/troubleshooting
> groundhog.day <- "2021-02-02"
> groundhog.library('Matrix', groundhog.day)
groundhog says: successfully loaded 'Matrix_1.3-2'.
> 
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Matrix_1.3-2    groundhog_1.2.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6      lattice_0.20-41 crayon_1.4.0    grid_4.0.3      lifecycle_0.2.0
 [6] magrittr_2.0.1  pillar_1.4.7    rlang_0.4.10    vctrs_0.3.6     ellipsis_0.3.1 
[11] forcats_0.5.1   tools_4.0.3     hms_1.0.0       xfun_0.20       compiler_4.0.3 
[16] pkgconfig_2.0.3 knitr_1.31      haven_2.3.1     tibble_3.0.6  
```

**Comment by urisohn** [comment]
It seems, then, that if one uses R Studio to work on .rmd files, one gives up version control on whatever packages R Studio decides to load automatically.

**Comment by urisohn** [comment]
There are work-arounds, but probably not sufficiently user friendly to enjoy wide adoption

**Comment by jimvine** [comment]
I have posted in the R Studio forum to see if that produces information on what the triggers are for R Studio to autoload packages: [When does R Studio autoload packages?](https://community.rstudio.com/t/when-does-r-studio-autoload-packages/96649)

I will report back here if it produces anything useful in terms of (I suspect) workarounds that others encountering this problem might be able to use.

**Comment by urisohn** [comment]
Great, thank you.

**Comment by urisohn** [comment]
Question, when you create the .rmd file, which options do you choose here:
![image](https://user-images.githubusercontent.com/56013245/108530540-fe00d500-72d5-11eb-8b17-67028bb47459.png)
i am trying to reproduce the problem to work on it

**Comment by jimvine** [comment]
I give it a title (just some text), put my name in the Author box, and use the HTML default output format.

**Comment by jimvine** [comment]
That produces an Rmd file with several sections of boilerplate text. I delete all that, so I'm only left with a brief YAML header and whatever chunks I want for my code.

**Comment by jimvine** [comment]
I think I have a minimum worked example here.

It comprises the chunk that I run with the groundhog stuff in it, and a chunk that calls dplyr below, **which I do not run**.

The output is pasted below. (On a different machine, so might be some odds and ends different from the earlier reports. But the same basic pattern is still shown. This machine is running R Studio 1.4.1103; the other is running v1.3.1073.)

I clear the environment. Restart R session. Check that `sessionInfo()` looks OK. Run just the groundhog chunk. Check `sessionInfo()` again.

```
> rm(list=ls())

Restarting R session...

> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.3 tools_4.0.3   
> 
> library(groundhog)
Loaded 'groundhog' (version:1.2.0) using R-4.0.3
Path to folder where downloaded packages are saved: 'C:/Users/[USERNAME]/Documents/R_groundhog/groundhog_library/'.
To change its location: 'set.groundhog.folder(<path>)'
     >>> If you encounter errors using groundhog: http://groundhogR.com/troubleshooting
> groundhog.day <- "2021-02-02"
> groundhog.library('Matrix', groundhog.day)
groundhog says: successfully loaded 'Matrix_1.3-2'.
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Matrix_1.3-2    groundhog_1.2.0

loaded via a namespace (and not attached):
 [1] lattice_0.20-41  crayon_1.4.0     dplyr_1.0.3      grid_4.0.3       R6_2.5.0        
 [6] lifecycle_0.2.0  magrittr_2.0.1   pillar_1.4.7     rlang_0.4.10     vctrs_0.3.6     
[11] generics_0.1.0   ellipsis_0.3.1   tools_4.0.3      glue_1.4.2       purrr_0.3.4     
[16] xfun_0.20        compiler_4.0.3   pkgconfig_2.0.3  tidyselect_1.1.0 knitr_1.31      
[21] tibble_3.0.6    
```

**Comment by jimvine** [comment]
GitHub won't let me attach an `.Rmd` file, so here it is with the file type changed to `.txt`.

[test_rstudio_loading_packages.txt](https://github.com/CredibilityLab/groundhog/files/6011667/test_rstudio_loading_packages.txt)

**Comment by urisohn** [comment]
Thanks. Yes, R Studio loads packages with the :: operator even if not run, if they are .rmd files. 
This is  bug for reproducibility purposes, but they may think of it as a feature. Wished it was an optional one.

**Comment by urisohn** [comment]
Am looking into giving a brute force solution via groundhog: removing from the local default library the packages that generate a conflict. `remove.package()`. This would prevent R Studio from loading them from the local library.

**Comment by jimvine** [comment]
Looking at the Rmd that I am mainly trying to use this with, I think that R Studio may be doing this even with commented out code. I had originally coded it using lots of `::` calls, since I find those more explicit in terms of where the function is coming from, but I think I removed them all when I decided to groundhog-ify my file. But I do have a fair amount of old versions left in there as commented out code.

So for my purposes, this is helpful just to know. I can probably go through the version of the file and remove the old commented out code or remove the `package::` prefixes within the commented code.

Thinking about options for groundhog (and with no idea of how easy / hard it would be, and without having thought through whether it would be suitable from a reproducibility standpoint), an alternative comes to my mind. Could groundhog (optionally) 'get in first'? Do the same as R Studio does with loading packages that are referenced via `::`, using groundhog's machinery to get the versions we want?

**Comment by urisohn** [comment]
I think ultimately the best practice will be for groundhog users to have very few packages in the local library, this will prevent R Studio from loading packages you do not call for.
For reproducibility purposes it's best to explicitly call any package one will use, even if relying on ::, so that future users of the same script run that same package. And groundhog couldn't do what R Studio does because the :: commands do not include a date.

But the solution i am working on will be the removal of the packages from the local library.

Upon running into a conflict users will be able to say "remove.conflict" those pacakges will be removed and then when restarting the session they will not be loaded behind the scenes. Apparently there are many triggers of phantom package loading, this will address all of them.

**Comment by jimvine** [comment]
> And groundhog couldn't do what R Studio does because the :: commands do not include a date.

I was envisaging a command like `groundhog.loadcolons(date)`, that could be run in the context of an Rmd and would go through to load all packages that are colon referenced.

I'm not saying it's a good idea! But that's how I was thinking of getting around the date issue.

**Comment by jimvine** [comment]
Having stripped out all my `::` references, this was almost working for me.

The last remaining hurdle is the xfun package. This seems to get loaded as soon as you do anything with any chunk in R Studio. And it also happens to be needed by one of the packages I'm using (sjPlot).

My main library contained the current version, v0.21. The version as at the groundhog.day I'm using was v0.20. v0.21 gets autoloaded as soon as I try to run the chunk, and hence the wrong version is loaded and prevents groundhog from loading sjPlot.

I tried `remove.packages("xfun")`. But then when I try to run code in the Rmd (either by clicking the play button on the chunk or by selecting the code and hitting Ctrl+Enter) it throws an error:

```
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘xfun’
```

I tried working around this by pasting the following into the Console:

```
library(groundhog)
groundhog.day <- "2021-02-02"
groundhog.library('xfun', groundhog.day)
```

That caused my R session to crash first time I did it. Re-trying it did work, but it doesn't seem like a great workaround since it seems that R Studio really expects the xfun package to be present.

So for now I've done:

```
devtools::install_version("xfun", version = "0.20")
```

That's a more successful workaround, but it's definitely a workaround. If the version of xfun in my main library ever gets updated, that will stop this file from working. If I start another reproducible project with a different groundhog.day, I will need the relevant xfun to be in my main library when running that.

**Comment by urisohn** [comment]
I suspect the crash that you observed followed from attempting to unload the package. Unloading is very messy in general, easy to get R to start crashing after attempting it.

The solution i have implemented is the following
1) groundhog has an optional argument of package conflicts to be ignored and allow installation to proceed without perfect version control, that argument now includes in the default both knitr and xfun, variables which R Studio very aggressively and repeatedly loads by default. Users get a warning that this happened.
2) If a conflict with any other package occurs, even after a restart, users are given the option to uninstall from their local library (non-groundhog) all packages generating that conflict. Then groundhog naturally proceeds uninterrupted as there are no conflicting packages for R Studio to load
3) When (2) occurs, the list of packages that are uninstalled gets saved, so that a user can, with a single command, and at any poiint, even months later, reinstall any packages they uninstalled. I don't think they will need or want to do that, but the option will be available.

The reason to exclude knitr and xfun is that people seem to like using the knit button in R Studio and it is not possible to use that button with packages available elsewhere. People who care maximally about version control can rely on a groundhog loaded markdown::knit, everyone else will have version control on everything except those packages.

I now need to submit this revised package to testing and will be submitting to CRAN v1.3.0

**Comment by urisohn** [comment]
If people are interested in trying it out, they can install the development version
install.packages("https://groundhogr.com/groundhog_1.3.0.9200.tar.gz",repos=NULL,type='source')

and then they can easily switch to the current CRAN version with
install.packages("groundhog")
