### ISSUE TITLE
recent dates invalid?

### ISSUE THREAD

**Issue by HedvigS** [CredibilityLab/groundhog#69]
I just tried out the package, loving the idea and implementation. I noticed that today, "2021-03-15" and "2021-03-16" are invalid as dates, but "2021-03-14" works. Is this systematically a thing, that the day of and the day before aren't valid?

**Comment by urisohn** [comment]
Yes. Because it can take a while for the package update to get implemented by all mirrors of CRAN. This way new scripts are 'guaranteed' to be loading the same package anywhere in the world.

**Comment by HedvigS** [comment]
Ah, understood! Thanks. That makes sense. If it's anywhere in any documentation, I must have missed it. If it isn't perhaps put it somewhere so people like me won't post the issue again :)
