### ISSUE TITLE
Bioconductor support

### ISSUE THREAD

**Issue by jasonbosch** [CredibilityLab/groundhog#76]
This looks like an interesting (and important) package but, currently, it will only go part-way to solving reproducible code in biological scripts. Many R scripts by biologists will use packages from Bioconductor (https://bioconductor.org/). I'm not sure whether the authors include biologists or not but I saw no mention of Bioconductor in either the Data Colada posts or the Groundhog website. Are there plans to include support for Bioconductor packages in the future?

**Comment by urisohn** [comment]
Yes, that's the next major change planned. Hopefully this summer

**Comment by jasonbosch** [comment]
That sounds great! I will definitely need to try it out then. It will also save me needing to specify package versions in my methods section (which few authors seem to do).

**Comment by urisohn** [comment]
i was planning to do that this april/may, but with MRAN disappearing it lost priority. 
Next time i return to working on groundhog i plan on doing it, perhaps around October of this year, but no promises.
If someone wants to collaborate and chip in with coding that would be welcomed too

**Comment by Lukas-1** [comment]
It would be amazing to have groundhog for Bioconductor. There are just so many advantages over renv.
