### ISSUE TITLE
groundhog.library failing to read connection

### ISSUE THREAD

**Issue by alexfradera** [CredibilityLab/groundhog#78]
Today I have been testing out knitting some .rmd code with calls to libraries within it, and for the first time trying to update these to use groundhog.library instead. This have been proving quite difficult  and I might separately document other parts of the issue (eg constantly looping "To ensure you are actively answering, only 'uninstall' and 'keep' are accepted as responses") and in the course of which I manually uninstalled and reinstalled stringi, which seems to be something that the knit process itself relies on. 

I don't know if that triggered something, but groundhog.library stopped running in any context, in any project, just as code - it just read

```
> groundhog.library("tidyverse", "2021-09-30")
Error in readRDS(toc.path) : error reading from connection
```

When I changed the groundhog path away from its normal one to another one, it began working again. Then it continued to work when I moved it back. However, I needed to repeat the process for different projects. And when it comes to the rmd knit, it seems impervious:

```
quitting from lines 13-58 (./SR_Report_Body.rmd)
Error in readRDS(toc.path) : error reading from connection
Calls: <Anonymous> ... groundhog.library.single -> get version -> toc -> load.cran.toc -> readRDS
```

I'm trying to figure out if I can find a way around this, or whether there are issues with trying to call groundhog from within a .rmd?

**Comment by urisohn** [comment]
Working on rmd files, with R Studio, while using groundhog is indeed tricky. The reason, I think, is that R Studio loads packages on its own, even pkgs not references in your scripts, making version control hard.  I think the new version of groundhog, not yet released, will be more resistant to this R Studio behavior. Version v.2.0.0 also will work with github and gitlab packages and am currently workign on addressing conflicts that arise in that context. Will test .rmd file conflicts next.  I think/hope that the new release will be ready in a matter of weeks, so maybe I would recommend to not use groundhog in your rmd files until that happens.

**Comment by alexfradera** [comment]
That's great, thank you, I'll take a different tack.

**Comment by alexfradera** [comment]
Hi Uri,

Great thanks for the update!

My thesis is going to the printer in less than a week so for my sanity I
will stick to things as-is, but will take a look at it afterward. Thanks
for looking into it, getting that working makes it massively helpful!

Best
Alex

**Comment by urisohn** [comment]
ok, i understand.
