### ISSUE TITLE
MRAN URL

### ISSUE THREAD

**Issue by nnlkcncff** [CredibilityLab/groundhog#81]
Please, add possibility to change MRAN URL, we are using JFrog Artifactory for proxing repos.

**Comment by urisohn** [comment]
Hi, i am not familiar with JFrog. Does it offer a mirror to MRAN or is it an alternative archive?
e.g., if you want to install, say, 'metafor' as available on 2020-06-01, how would you request that from JFrog?

**Comment by nnlkcncff** [comment]
It will be something like this:
```
R -e '
  options(repos = c("CRAN" = "https://${jfrog-domain-name}/artifactory/cran-remote"))
  groundhog::groundhog.library("metafor", "2020-06-01")
'
```
Artifactory is a web application with a lot of repository facilities, located on some node in the internal network.

In this context, its main function is to proxy an external repository.
Artifactory accepts requests from package managers and transfers data between external repository and package manager and caches received data, i.e. packages received through Artifactory remain in Artifactory cache.

All kinds of packages are supported, not only CRAN, e.g. DEB, RPM, PHP Composer, Docker...

Here is full list of supported packages:
https://www.jfrog.com/confluence/display/JFROG/Package+Management

In my example, Artifactory provides the link `https://${jfrog-domain-name}/artifactory/cran-remote` -> `https://cran.r-project.org/`.

**Comment by urisohn** [comment]
I don't understand what is gained by using jfrog. What's a use case where an R user wants to install a package and actively prefers to avoid using the default MRAN location for it?

**Comment by nnlkcncff** [comment]
I apologize for the delay in the answer. At the moment, I am not connected with the project, in which I have been useful to me the functionality I requested.

You ask what is the reason for avoiding the standard MRAN?

The security policy of many corporations limits direct Internet access. Products like Sonatype Nexus and JFrog Artifactory proxying external resources, caching data, allow you to create their own repositories... These products become a single access point to any artifacts in many companies and institutions.

Returning to our specific case, it turns out that the mirror of the MRAN repository appears in the companies, the condition of which is constantly updated to match with the original MRAN, that is, only the link changes, but reproducibility remains.

The use of repository management software pushes not only inner policies — these are convenient and useful tools for modern development processes, sometimes even necessary (for example, the maximum number of possible appeals in a certain period of time is limited to some repositories).

In addition, CRAN snapshots have not only MRAN, but also RSPM (RStudio Package Manager), and, possibly, in some other repositories MRAN is not the only public provider of CRAN snapshots.

Examples of repository managers:
  - https://www.peerspot.com/categories/repository-managers

More about RSPM:
  - https://packagemanager.rstudio.com/
  - https://packagemanager.rstudio.com/client/#/repos/2/overview
  - https://docs.rstudio.com/rspm/admin/appendix/source-details/#cran-snapshot-source

**Comment by urisohn** [comment]
OK, I understand. I think that use case is too far from the use case for which groundhog is designed for (long-term reproducibility of academic research) so I don't see myself working on incorporating it. If someone else wanted to build a separate package, though, that would be great and happy to share any info on how groundhog does this or that which may prove useful to them
