### ISSUE TITLE
Can't load development branch of GitHub package

### ISSUE THREAD

**Issue by theamarks** [CredibilityLab/groundhog#82]
I am running a biblometric analysis based on the development branch of a GitHub package ([here](https://github.com/DataONEorg/scythe/tree/develop)). I would like to make my analysis reproducible and maintain the exact version of the package. 

The regular instillation of the development branch is `devtools::install_github("dataoneorg/scythe@develop")` and I have tried to use groundhog like this: `groundhog.library('github::dataoneorg/scythe@develop' , '2022-07-14')`

I am running into an error trying to employ groundhog with the development branch of this package. `Unable to obtain R package 'dataoneorg/scythe@develop' from 'github'. Check spelling of package, make sure it is an R package, and that it is available on 'github',  check your internet connection [...]`

Is this function available with groundhog? Thanks for such a fantastic package!

**Comment by urisohn** [comment]
Hi. Yeah, groundhog only works with the default branch, this is unlikely to be modified. 
Future versions of groundhog should add useful feedback to communicate this when a user specifies the branch in the call with @. 

Sorry.

**Comment by theamarks** [comment]
No worries, thank you for the clarification!
