### ISSUE TITLE
Which path should I use to install groundhog?

### ISSUE THREAD

**Issue by shankswine** [CredibilityLab/groundhog#94]
When I ran "library("groundhog")", I got the following message:
|       The path '/Users/username/R_groundhog/groundhog_library/ seems to be a 
|       on a different drive (or 'volume') than the default R library 
|       '/Library/Frameworks/R.framework/Versions/4.2/Resources/library'. 
|       Groundhog will be slower and more likely to produce occasional errors 
|       if paths for libraries are on different drives. It is strongly 
|       recommended to use the same physical drive for both paths instead. If 
|       you want to set it to  '/Users/kewang/R_groundhog/groundhog_library/' 
|       anyway, type 'anyway', else type 'cancel' 

Which path should I use to install groundhog? Should I type 'anyway' or choose /Library, or /Library/Frameworks, or /Library/Frameworks/R.framework or move the default R library? Thank you in advance for your help!

**Comment by urisohn** [comment]
**short answer**: type 'anyway'

**longer answer:** 
The check for multiple drives, added in v3.0.0, produces more false-positive than expected, this is almost surely a false positive so I would suggest going with "anyway". I am finalizing an update fixing bugs identified in this major re-rewrite, and this check will be replaced with a much more accurate one.

**Comment by shankswine** [comment]
Thank you so much, Uri!
