### ISSUE TITLE
need to call groundhog.library() twice in docker 

### ISSUE THREAD

**Issue by arraytools** [CredibilityLab/groundhog#96]
Thanks for the wonderful package. I found a case that I need to call groundhog.library() twice in order to install packages inside a docker environment. 

```
$ docker run -it --rm rocker/verse:4.3.0 bash
root@58978695ec12:/# R
R version 4.3.0 (2023-04-21) -- "Already Tomorrow"
...
> install.packages("groundhog"); library(groundhog)
> packageVersion("groundhog")
[1] ‘3.1.0’

> groundhog.library("DT", "2023-4-23")
groundhog needs authorization to save files to '/root/R_groundhog/'
Enter 'OK' to provide authorization, and 'NO' not to.
|   >OK
...
* DONE (DT)
---------------------------------------------------------------------------
|   IMPORTANT.
|       Will switch to slower 'copying-and-deleting' method going
|
|       gives additional information.
**Groundhog stopped**

There were 36 warnings (use warnings() to see them)
> find.package("DT")
Error in find.package("DT") : there is no package called ‘DT’

> # Try it again.
> groundhog.library("DT", "2023-4-23")
Will now copy 36 packages to /root/R_groundhog/groundhog_library//restore_library/4.3
...
> find.package("DT")
[1] "/usr/local/lib/R/site-library/DT"
```

Wonder if this is related to docker or groundhog. Thanks in advance.

**Comment by urisohn** [comment]
This behavior is supposed to happen when groundhog fails to use the renaming method to quickly move a file from the groundhog library to R's default library (groundhog moves pkgs from/to the local folder, and renaming them is very fast, but only works if both paths are in the same physical drive)

Two questions
1)  If you do .libPaths() and get.groundhog.library(), do you get paths on different physical drives or the same?
2) Groundhog is supposed to remember the renaming method failed, and from then onwards not attempt it, so you should only need to run it twice on the first pass. If you restart the r session and try to use groundohg again, i think it will work on the first attempt. Does it?

Thanks for reaching out.

**Comment by urisohn** [comment]
I am a little unclear on whether after restarting R, while still within the same docker, you can run groundhog.library() and works at first or whether in that scenario you again need to run it twice.

This was not meant to do something users would directly do, but you can directly tell groundhog to always copy instead of rename by running:

`groundhog:::save.cookie("copy_instead_of_renaming")`


If you put that once at the top of the script, it will never try the faster renaming method.

**Comment by arraytools** [comment]
The call `groundhog:::save.cookie("copy_instead_of_renaming")` does the trick. Now I don't need to call groundhog.library() twice to install the packages I need. 
Thanks:)
